"""phase 2.1: facturas items pagos movimientos stock_sucursal

Revision ID: 03be592f9146
Revises: d49c6d370695
Create Date: 2026-04-24 15:39:26.443369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03be592f9146'
down_revision = 'd49c6d370695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('factura_a', 'factura_b', 'factura_c', 'ticket', 'nota_credito_a', 'nota_credito_b', 'nota_credito_c', 'remito', 'presupuesto', name='tipo_comprobante_enum'), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cajero_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'emitida', 'anulada', name='estado_comprobante_enum'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=False),
    sa.Column('cotizacion', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('cae', sa.String(length=32), nullable=True),
    sa.Column('cae_vencimiento', sa.Date(), nullable=True),
    sa.Column('qr_afip', sa.Text(), nullable=True),
    sa.Column('anulada_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulada_por_user_id', sa.Integer(), nullable=True),
    sa.Column('factura_origen_id', sa.Integer(), nullable=True),
    sa.Column('legacy_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['anulada_por_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cajero_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['factura_origen_id'], ['facturas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sucursal_id', 'punto_venta', 'tipo', 'numero', name='uq_facturas_suc_pv_tipo_nro')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_cajero_id'), ['cajero_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_factura_origen_id'), ['factura_origen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_sucursal_id'), ['sucursal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_tipo'), ['tipo'], unique=False)

    op.create_table('caes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('cuit_emisor', sa.String(length=13), nullable=False),
    sa.Column('tipo_afip', sa.Integer(), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cae', sa.String(length=14), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proveedor', sa.String(length=30), nullable=False),
    sa.Column('request_xml', sa.Text(), nullable=True),
    sa.Column('response_xml', sa.Text(), nullable=True),
    sa.Column('qr_url', sa.Text(), nullable=False),
    sa.Column('obs_afip', sa.Text(), nullable=True),
    sa.Column('resultado', sa.String(length=1), nullable=False),
    sa.Column('reproceso', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caes_cae'), ['cae'], unique=False)
        batch_op.create_index(batch_op.f('ix_caes_cuit_emisor'), ['cuit_emisor'], unique=False)
        batch_op.create_index(batch_op.f('ix_caes_factura_id'), ['factura_id'], unique=True)

    op.create_table('factura_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('medio', sa.Enum('efectivo', 'tarjeta_debito', 'tarjeta_credito', 'transferencia', 'qr_mercadopago', 'qr_modo', 'cheque', 'cuenta_corriente', 'vale', name='medio_pago_enum'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factura_pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factura_pagos_factura_id'), ['factura_id'], unique=False)

    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('caja_numero', sa.Integer(), nullable=False),
    sa.Column('fecha_caja', sa.Date(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.Enum('venta', 'devolucion', 'cobranza', 'pago_proveedor', 'apertura_caja', 'cierre_caja', 'ingreso_efectivo', 'egreso_efectivo', 'ajuste', 'cheque_recibido', 'cheque_entregado', name='tipo_movimiento_enum'), nullable=False),
    sa.Column('medio', sa.Enum('efectivo', 'tarjeta_debito', 'tarjeta_credito', 'transferencia', 'qr_mercadopago', 'qr_modo', 'cheque', 'cuenta_corriente', 'vale', name='medio_pago_enum'), nullable=True),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_caja_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_factura_id'), ['factura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_fecha_caja'), ['fecha_caja'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_sucursal_id'), ['sucursal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_caja_tipo'), ['tipo'], unique=False)

    op.create_table('factura_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('descuento_porc', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('iva_porc', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('iva_monto', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factura_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factura_items_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_factura_items_factura_id'), ['factura_id'], unique=False)

    op.create_table('stock_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('articulo_id', 'sucursal_id', name='uq_stock_art_suc')
    )
    with op.batch_alter_table('stock_sucursal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_sucursal_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_sucursal_sucursal_id'), ['sucursal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sucursal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_sucursal_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_stock_sucursal_articulo_id'))

    op.drop_table('stock_sucursal')
    with op.batch_alter_table('factura_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factura_items_factura_id'))
        batch_op.drop_index(batch_op.f('ix_factura_items_articulo_id'))

    op.drop_table('factura_items')
    with op.batch_alter_table('movimientos_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_fecha_caja'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_fecha'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_factura_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_caja_cliente_id'))

    op.drop_table('movimientos_caja')
    with op.batch_alter_table('factura_pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factura_pagos_factura_id'))

    op.drop_table('factura_pagos')
    with op.batch_alter_table('caes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caes_factura_id'))
        batch_op.drop_index(batch_op.f('ix_caes_cuit_emisor'))
        batch_op.drop_index(batch_op.f('ix_caes_cae'))

    op.drop_table('caes')
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_tipo'))
        batch_op.drop_index(batch_op.f('ix_facturas_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_fecha'))
        batch_op.drop_index(batch_op.f('ix_facturas_factura_origen_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_estado'))
        batch_op.drop_index(batch_op.f('ix_facturas_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_cajero_id'))

    op.drop_table('facturas')
    # ### end Alembic commands ###
