"""initial schema

Revision ID: d49c6d370695
Revises: 
Create Date: 2026-04-24 12:39:21.274031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49c6d370695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('cuit', sa.String(length=15), nullable=True),
    sa.Column('condicion_iva', sa.Enum('responsable_inscripto', 'monotributo', 'consumidor_final', 'exento', 'no_categorizado', name='condicion_iva_enum'), nullable=False),
    sa.Column('condicion_iva_receptor_id', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('cuenta_corriente', sa.Boolean(), nullable=False),
    sa.Column('limite_cuenta_corriente', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_cuit'), ['cuit'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_razon_social'), ['razon_social'], unique=False)

    op.create_table('familias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('familias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_familias_codigo'), ['codigo'], unique=True)

    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marcas_nombre'), ['nombre'], unique=True)

    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('cuit', sa.String(length=15), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_proveedores_cuit'), ['cuit'], unique=False)

    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sucursales_codigo'), ['codigo'], unique=True)

    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sucursal_id', 'codigo', name='uq_areas_sucursal_codigo')
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_sucursal_id'), ['sucursal_id'], unique=False)

    op.create_table('rubros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('familia_id', 'codigo', name='uq_rubros_familia_codigo')
    )
    with op.batch_alter_table('rubros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubros_familia_id'), ['familia_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'supervisor', 'cajero', 'fiambrero', 'repositor', 'contador', name='rol_enum'), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('subrubros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubro_id', 'codigo', name='uq_subrubros_rubro_codigo')
    )
    with op.batch_alter_table('subrubros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subrubros_rubro_id'), ['rubro_id'], unique=False)

    op.create_table('articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('descripcion_corta', sa.String(length=100), nullable=True),
    sa.Column('familia_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('subrubro_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_principal_id', sa.Integer(), nullable=True),
    sa.Column('unidad_medida', sa.Enum('unidad', 'kg', 'gr', 'lt', 'ml', name='unidad_medida_enum'), nullable=False),
    sa.Column('controla_stock', sa.Boolean(), nullable=False),
    sa.Column('controla_vencimiento', sa.Boolean(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pvp_base', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('iva_porc', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['familia_id'], ['familias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proveedor_principal_id'], ['proveedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subrubro_id'], ['subrubros.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articulos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_articulos_codigo_barras'), ['codigo_barras'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_descripcion'), ['descripcion'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_familia_id'), ['familia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_marca_id'), ['marca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_proveedor_principal_id'), ['proveedor_principal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_rubro_id'), ['rubro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulos_subrubro_id'), ['subrubro_id'], unique=False)

    op.create_table('articulo_proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('codigo_proveedor', sa.String(length=50), nullable=True),
    sa.Column('costo_proveedor', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('ultimo_ingreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('articulo_id', 'proveedor_id', name='uq_artprov_art_prov')
    )
    with op.batch_alter_table('articulo_proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articulo_proveedores_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulo_proveedores_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('precios_historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('precio_anterior', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('precio_nuevo', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cambiado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cambiado_por_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precios_historicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precios_historicos_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_historicos_sucursal_id'), ['sucursal_id'], unique=False)

    op.create_table('precios_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('precios_sucursal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_precios_sucursal_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_precios_sucursal_sucursal_id'), ['sucursal_id'], unique=False)
        batch_op.create_index('uq_precio_sucursal_activo', ['articulo_id', 'sucursal_id'], unique=True, sqlite_where=sa.text('activo = 1'), postgresql_where=sa.text('activo = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('precios_sucursal', schema=None) as batch_op:
        batch_op.drop_index('uq_precio_sucursal_activo', sqlite_where=sa.text('activo = 1'), postgresql_where=sa.text('activo = true'))
        batch_op.drop_index(batch_op.f('ix_precios_sucursal_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_precios_sucursal_articulo_id'))

    op.drop_table('precios_sucursal')
    with op.batch_alter_table('precios_historicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_precios_historicos_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_precios_historicos_articulo_id'))

    op.drop_table('precios_historicos')
    with op.batch_alter_table('articulo_proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articulo_proveedores_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_articulo_proveedores_articulo_id'))

    op.drop_table('articulo_proveedores')
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articulos_subrubro_id'))
        batch_op.drop_index(batch_op.f('ix_articulos_rubro_id'))
        batch_op.drop_index(batch_op.f('ix_articulos_proveedor_principal_id'))
        batch_op.drop_index(batch_op.f('ix_articulos_marca_id'))
        batch_op.drop_index(batch_op.f('ix_articulos_familia_id'))
        batch_op.drop_index(batch_op.f('ix_articulos_descripcion'))
        batch_op.drop_index(batch_op.f('ix_articulos_codigo_barras'))
        batch_op.drop_index(batch_op.f('ix_articulos_codigo'))

    op.drop_table('articulos')
    with op.batch_alter_table('subrubros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subrubros_rubro_id'))

    op.drop_table('subrubros')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rubros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rubros_familia_id'))

    op.drop_table('rubros')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_sucursal_id'))

    op.drop_table('areas')
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sucursales_codigo'))

    op.drop_table('sucursales')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_cuit'))
        batch_op.drop_index(batch_op.f('ix_proveedores_codigo'))

    op.drop_table('proveedores')
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marcas_nombre'))

    op.drop_table('marcas')
    with op.batch_alter_table('familias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_familias_codigo'))

    op.drop_table('familias')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_razon_social'))
        batch_op.drop_index(batch_op.f('ix_clientes_cuit'))
        batch_op.drop_index(batch_op.f('ix_clientes_codigo'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
