"""comercio config singleton

Revision ID: f06aff01a31a
Revises: 03be592f9146
Create Date: 2026-04-25 00:13:54.114466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06aff01a31a'
down_revision = '03be592f9146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercio_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nombre_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cuit', sa.String(length=13), nullable=False),
    sa.Column('condicion_iva', sa.String(length=40), nullable=False),
    sa.Column('domicilio', sa.String(length=200), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('iibb', sa.String(length=50), nullable=True),
    sa.Column('inicio_actividades', sa.Date(), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('pie_ticket', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comercio_config')
    # ### end Alembic commands ###
